-keep class com.hikvision.netsdk.** { *; }
-keep class com.sd.lib.hikvision.HikVisionException
-keep class * extends com.sd.lib.hikvision.HikVisionException
-keep class * extends com.sd.lib.hikvision.HikPlayer